### ISSUE TITLE
Nacharbeiten ODD

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/opendataday#12]
* Vorträge online stellen
  * Sensebox
  * Open Government
  * Thore
  * MachMitMünster
  * Verlinken: MünsterWiki
  * Verlinken: RepairCafes
  * "Den Lehrer von Tobi"
  * Unfallstatistiken

* [x] Fotos von MachMitMünster herunterladen
* [x] Zeitungsfrau anmailen nabila.lalee, at gmail co, WN - lokalredaktion münster stadt, Fotos an die Zeitungsfrau schreiben
* [x] Schönes Morgen Münster anmailen - dr ulrike blanc münster marketing blanc stadt-muenster.de

**Comment by silberzwiebel** [comment]
Ich denke dieses issue kann zu? ODD 2017 ...
