### ISSUE TITLE
Improve Layout on small displays

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/opendataday#20]
The page is live on http://codeformuenster.org/opendataday/

Right now, the page isn't optimized for displays with less than 945 pixels in width so it does not look nice on mobile phones.

**Comment by KarlaChen** [comment]
Hi, @ubergesundheit , can I try it?

**Comment by ubergesundheit** [comment]
> Hi, @ubergesundheit , can I try it?

Sure! :)
