### ISSUE TITLE
Open Data Day 2020 Website Todos

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/opendataday#23]
TODO
- [x] Smooth scrollen bei Klick auf die Tabs https://stackoverflow.com/questions/12102118/scrollintoview-animation
- [x] Infos zu den Ständen im Lesesaal
- [x] Hinweise auf OpenDataQuiz & Senseboxen Ausprobiererei
- [x] Agenda anpassen

Nice to have
- [ ] Seite etwas auflockern durch Impressionsbilder/Fotos/Cliparts
- [x] Leiste der Logos der teilnehmenden Organisationen mit einbauen

**Comment by ubergesundheit** [comment]
- [x] /2020/ nach / umziehen
- [x] `<title>` anpassen
- [x] Responsiveness

**Comment by tomsrocket** [comment]
Was fehlt Dir noch zum Thema "responsiveness"? Da hatte ich extra drauf geachtet dass es flexible Bildschirmgrößen und auch Handys unterstützt.

**Comment by ubergesundheit** [comment]
Bei mir auf dem Mobiltelefon sieht es so aus: 
![0947AB14-CD1D-493B-AFF7-DB57D7A9B33A](https://user-images.githubusercontent.com/1494211/74198796-ac555180-4c62-11ea-9d06-db2e46dc8c48.png)

**Comment by webwurst** [comment]
Firefox, Android, Fairphone:
![Screenshot_20200211-001516](https://user-images.githubusercontent.com/225698/74199300-0efb1d00-4c64-11ea-89bc-b029a63daffe.png)

**Comment by tomsrocket** [comment]
Danke! Ich hatte es leider nur in der Handy-Simulation im Browser ausprobiert 🙈 Ich erinnere mich dass ich das Problem mit dem Bulma CSS Framework schon öfter hatte.. Ich versuche das mal zu fixen

**Comment by ubergesundheit** [comment]
Im HTML fehlt das meta tag dafür..
```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

**Comment by tomsrocket** [comment]
Super, das hat geklappt, danke!
