### ISSUE TITLE
Vorschlag Agenda

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/opendataday#7]
15 Minuten Slots

Alle kommen an, Kaffee (ab 9)
- 10 uhr Begrüßung, Wer sind wir, was machen wir eigentlich (Gerald)
- Data Hub/Open events (Tobias, Thomas)
- Sensebox (Christoph)
  -???
- "Was hat Dich am Praxis Alltag als Informatiklehrer am meisten erstaunt im Vergleich zur Theorie, wie steht es um den Informatikernachwuchs und so :-)"
- kleiner Einstieg Open Data (Thomas)
- Pizza
- Hacken

**Comment by tomsrocket** [comment]
LOL - Das in der Mitte könnte man auch erstmal nennen "Die Rolle von Open Data im Informatikunterricht" - ich klär das noch mit Olli. 
Und Freifunk Münsterland wird wahrscheinlich auch was erzählen.
